version: "3"

services:
  poll:
    build: ./poll
    logging:
      driver: none
    ports:
    - "5000:80"
    networks:
      - poll-tier

  redis:
    image: redis:3.2-alpine
    restart: always
    expose: 
    - "6379"
    ports:
    - "6379"
    logging:
      driver: none
    networks:
      - poll-tier
      - back-tier

  worker:
    build: ./worker
    environment:
      WORKER_HOST: 127.0.0.1
    logging:
      driver: none
    networks:
      - back-tier

  db:
    image: postgres:10
    logging:
      driver: none
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PWD: password
      POSTGRES_DB: db
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - result-tier
      - back-tier

  result:
    build: ./result
    logging:
      driver: none
    ports:
    - "5001:80"
    expose:
      - "80"
    networks:
      - result-tier

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
