#!/bin/python3

import sys
from reedpipes import initF, initR, columnM, columnCC2, interpolation, printM, print_res
from Point import *

def usage():
	print("USAGE\n" +
"    ./308reedpipes r0 r5 r10 r15 r20 n\n" +
"DESCRIPTION\n" +
"    r0      radius(in cm) of pipe at the 0cm abscissa\n" +
"    r5      radius(in cm) of pipe at the 5cm abscissa\n" +
"    r10     radius(in cm) of pipe at the 10cm abscissa\n" +
"    r15     radius(in cm) of pipe at the 15cm abscissa\n" +
"    r20     radius(in cm) of pipe at the 20cm abscissa\n" +
"    n       number of points needed to display the radius\n")

def args():
	print("Wrong arguments")
	exit(84)

def main(argv):
	if len(argv) == 2 and argv[1] == "-h":
		usage()
	elif len(argv) == 7:
		try:
			points = []
			points.append(Point(0, float(argv[1])))
			points.append(Point(5, float(argv[2])))
			points.append(Point(10, float(argv[3])))
			points.append(Point(15, float(argv[4])))
			points.append(Point(20, float(argv[5])))
			check_points(points)
			n = int(argv[6])
			if (n <= 0):
				args()
		except ValueError:
			args()
		initF(points)
		R = initR(points)
		M = columnM(points, R)
		(C, C2) = columnCC2(points, M)
		printM(M)
		print_res(points, n, M, C, C2)
	else:
		usage()
		exit(84)
	exit(0)

if __name__ == "__main__":
	main(sys.argv)
