// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomBarChart: typeof import('./components/Charts/CustomBarChart.vue')['default']
    CustomLineChart: typeof import('./components/Charts/CustomLineChart.vue')['default']
    DatasetBaseStats: typeof import('./components/DatasetBaseStats.vue')['default']
    DatasetMovieByGenreStats: typeof import('./components/DatasetMovieByGenreStats.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LayoutDefault: typeof import('./layouts/layout-default.vue')['default']
    MovieCard: typeof import('./components/MovieCard.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./components/StatCard.vue')['default']
  }
}

export {}
